# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 440)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(640, 480))
        MainWindow.setStyleSheet("background-color: rgb(255, 234, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 400, 400))
        self.graphicsView.setStyleSheet("background-color: rgb(255, 254, 217);")
        self.graphicsView.setObjectName("graphicsView")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(470, 40, 140, 25))
        self.comboBox.setStyleSheet("background-color: rgb(255, 254, 217);")
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(470, 100, 140, 25))
        self.spinBox.setStyleSheet("background-color: rgb(255, 254, 217);")
        self.spinBox.setMaximum(180)
        self.spinBox.setProperty("value", 80)
        self.spinBox.setObjectName("spinBox")
        self.N_label = QtWidgets.QLabel(self.centralwidget)
        self.N_label.setGeometry(QtCore.QRect(430, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.N_label.setFont(font)
        self.N_label.setObjectName("N_label")
        self.R_label = QtWidgets.QLabel(self.centralwidget)
        self.R_label.setGeometry(QtCore.QRect(430, 100, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.R_label.setFont(font)
        self.R_label.setObjectName("R_label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(410, 160, 221, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.S_label = QtWidgets.QLabel(self.centralwidget)
        self.S_label.setGeometry(QtCore.QRect(430, 210, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.S_label.setFont(font)
        self.S_label.setObjectName("S_label")
        self.S_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.S_lineEdit.setGeometry(QtCore.QRect(470, 210, 140, 25))
        self.S_lineEdit.setStyleSheet("background-color: rgb(255, 254, 217);")
        self.S_lineEdit.setText("")
        self.S_lineEdit.setReadOnly(True)
        self.S_lineEdit.setObjectName("S_lineEdit")
        self.Pi_label = QtWidgets.QLabel(self.centralwidget)
        self.Pi_label.setGeometry(QtCore.QRect(430, 270, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Pi_label.setFont(font)
        self.Pi_label.setObjectName("Pi_label")
        self.Pi_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Pi_lineEdit.setGeometry(QtCore.QRect(470, 270, 140, 25))
        self.Pi_lineEdit.setStyleSheet("background-color: rgb(255, 254, 217);")
        self.Pi_lineEdit.setReadOnly(True)
        self.Pi_lineEdit.setObjectName("Pi_lineEdit")
        self.calculation_Button = QtWidgets.QPushButton(self.centralwidget)
        self.calculation_Button.setGeometry(QtCore.QRect(420, 330, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.calculation_Button.setFont(font)
        self.calculation_Button.setStyleSheet("background-color: rgb(113, 255, 103);")
        self.calculation_Button.setObjectName("calculation_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MonteCarlo"))
        self.comboBox.setItemText(0, _translate("MainWindow", "100"))
        self.comboBox.setItemText(1, _translate("MainWindow", "500"))
        self.comboBox.setItemText(2, _translate("MainWindow", "1000"))
        self.comboBox.setItemText(3, _translate("MainWindow", "2000"))
        self.comboBox.setItemText(4, _translate("MainWindow", "3000"))
        self.comboBox.setItemText(5, _translate("MainWindow", "4000"))
        self.comboBox.setItemText(6, _translate("MainWindow", "5000"))
        self.N_label.setText(_translate("MainWindow", "N"))
        self.R_label.setText(_translate("MainWindow", "R"))
        self.S_label.setText(_translate("MainWindow", "S"))
        self.Pi_label.setText(_translate("MainWindow", "Pi"))
        self.calculation_Button.setText(_translate("MainWindow", "Вычислить"))

